spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    main:
      allow-bean-definition-overriding:true:
app:
  rabbitmq:
    queuename:  queue.fanout
    exchange: queue.demofanoutmulti
    routingkey: queue.demofanoutmultiKey
health:
  rabbit:
    enabled:false:
